### ISSUE TITLE
mpx 插件在m1 的vscode上功能无效

### ISSUE THREAD

**Issue by uni7corn** [mpx-ecology/vscode-mpx#32]
mac最新系统
前置条件：mpx项目，已安装好mpx插件，并已在工作区配置好setting.json
实际值：mpx 插件对xx.mpx类型文件，无效或完全不起作用。比如在js标签域中，完全无代码提示等作用
期望值：在m1 版本得vscode当中mpx插件也可用

备注：mac 系统最新版，在m1 版本得vscode上mpx 插件无效果，但是在Intel的vscode 版本的mpx插件有效果

<img width="1143" alt="Screen Shot 2021-06-07 at 16 05 49" src="https://user-images.githubusercontent.com/8399829/120981989-cba6b500-c7aa-11eb-820f-883ea5a7b1f5.png">

<img width="910" alt="Screen Shot 2021-06-07 at 16 03 43" src="https://user-images.githubusercontent.com/8399829/120981191-fcd2b580-c7a9-11eb-866d-140022debae3.png">

<img width="937" alt="Screen Shot 2021-06-07 at 16 03 50" src="https://user-images.githubusercontent.com/8399829/120981211-02300000-c7aa-11eb-9f53-01fbf298982c.png">

**Comment by pagnkelly** [comment]
具体表现是？颜色没有高亮，api提示等功能都没有吗

**Comment by pagnkelly** [comment]
非常尴尬的是，我周围没有m1的电脑可供我来调试

**Comment by uni7corn** [comment]
颜色既没高丽，也没api代码功能提示，反正就是mpx插件完全不起作用。。这就尴尬了

**Comment by uni7corn** [comment]
颜色既没高亮，也没有任何api代码功能提示，反正就是mpx插件完全不起作用。。

只能通过配置第三方vetur进行开发，体验没有mpx好。

这个就尴尬了，快去叫老板买一台。性能真香警告

**Comment by pagnkelly** [comment]
希望老板能看到这个issues,你也可以尝试提供pr来解决此问题

**Comment by uni7corn** [comment]
我重新装了arm 版本的vscode，可以正常使用了，感谢你们的付出
