### ISSUE TITLE
无法完成自动格式化

### ISSUE THREAD

**Issue by LikeDreamwalker** [mpx-ecology/vscode-mpx#33]
<img width="386" alt="QQ20210625-113240@2x" src="https://user-images.githubusercontent.com/45194556/123365597-23199300-d5a9-11eb-9776-4c98ea470859.png">
可以正常高亮，但是格式化不行，尝试手动配置也没有效果，求指路

**Comment by wuxianqiang** [comment]
根据图片提供的提示内容发现你在格式化mpx文件的时候使用了prettier插件，可以尝试先卸载prettier插件。当第一次格式化mpx文件的时候vscode会弹窗提示你选择是mpx或者prettier，这时你选择mpx插件格式化。如果以上办法还是不能决解，你可以写demo贴出你的代码我检测一下。

**Comment by LikeDreamwalker** [comment]
感谢提醒，问题已经得到解决。

我的情况是我配置了默认的格式化插件（prettier），而prettier不支持MPX的格式化，导致了这个问题。

解决方案就是取消默认的格式化配置或者手动指定MPX的格式化插件为vscode-mpx。

主要混淆的点是vscode-mpx中也有和prettier相关的内容，但其实应该将MPX的格式化完全交给vscode-mpx而不是prettier

https://zhuanlan.zhihu.com/p/383901560
