### ISSUE TITLE
格式化无法识别非标签包裹的语句

### ISSUE THREAD

**Issue by LikeDreamwalker** [mpx-ecology/vscode-mpx#34]
<img width="719" alt="QQ20210625-163225@2x" src="https://user-images.githubusercontent.com/45194556/123395907-4bb68280-d5d3-11eb-912d-9da0e3a48b4a.png">

目前测试的结果是，prettier配置可用，格式化可用（通过改变tabs测试），但是对于标签下非标签包裹的语句会取消缩进，应该是缺少了某个属性导致的。格式化后会出现图中的现象。

我尝试在settings.json和.prettierrc中配置相关内容，但是都不能改变这一点（包括直接导出prettier官方的配置json存储在prettierrc中），不过其他的配置都是生效的。

这可能是哪里的问题？目前使用最新版，直接指定mpx的格式化插件为vscode-mpx。

**Comment by wuxianqiang** [comment]
我不太明白你的意思，什么是：标签下非标签包裹的语句。你是说图片中的 `{{ item }}` 想要取消两边的空格变成 `{{item}}` 是吗？如果是这个功能的化，目前是不支持的，只能手动人工处理。

**Comment by LikeDreamwalker** [comment]
可能我表达的不是很清楚，在未格式化之前（MPX生成的模版）格式如下：
<img width="545" alt="QQ20210628-145549@2x" src="https://user-images.githubusercontent.com/45194556/123593545-36cf2e80-d821-11eb-8190-29859bcc8f46.png">
在完成格式化后，script标签内的所有语句都失去了本应拥有的相对于script标签的缩进，但是各个语句之间的缩进是依然存在的；
<img width="559" alt="QQ20210628-145638@2x" src="https://user-images.githubusercontent.com/45194556/123593661-5d8d6500-d821-11eb-8f64-cb414b767905.png">
而对于HTML来说，则没有任何问题：
<img width="726" alt="QQ20210628-145649@2x" src="https://user-images.githubusercontent.com/45194556/123593711-6b42ea80-d821-11eb-860a-865fc1098a5f.png">
所以我定位到的问题是插件对于语句识别不准确，或者是由于环境中某些配置冲突导致js和html变得“独立”了，我并不清楚原因，这是我的猜测。这种问题的原因可能是什么呢？

**Comment by wuxianqiang** [comment]
目前我们还不支持这个功能！

因为 mpx 在格式化的时候是每个区域（如：html，js，css）的代码分别传给 prettier  进行处理的，template 默认会包含在内当作整体去识别，而 JS 会去掉 script 标签，把里面的内容拿出来再传递给 prettier 去处理（因为`<script><script>`标签不是JS语法）。同理 css 也是这样。所以导致了 script 和 css 标签的缩进都是顶格排列。

**Comment by LikeDreamwalker** [comment]
好吧，希望可以尽快加入这个功能！
