### ISSUE TITLE
mpx2.7项目js代码格式化和eslint不生效

### ISSUE THREAD

**Issue by chaucerling** [mpx-ecology/vscode-mpx#51]
https://github.com/chaucerling/mpx-demo-2.7

vscode 1.65.2, 已安装 eslint, prettier, mpx 插件

使用了mpx-eslint-parser 编译 mpx 文件，babel-eslint 编译 js 代码

template 和 json 能正常格式化，但是js代码不行

**Comment by chaucerling** [comment]
控制台mpx的输出
```
"Prettier format failed"
[Error - 上午1:30:43] Couldn't resolve parser "babylon"
```

**Comment by pagnkelly** [comment]
已经在看了，可以给script标签加上lang="ts" 尝试解决

**Comment by wuxianqiang** [comment]
你试试这个配置，然后重启编辑。应该是2.6.x版本编辑器的问题，2.5.x的时候是正常的。
![clipboard_image_1648534066630](https://user-images.githubusercontent.com/26681854/160565831-852fa122-d8f6-4c6f-afd8-7ed39df0bfac.png)

**Comment by chaucerling** [comment]
> 你试试这个配置，然后重启编辑。应该是2.6.x版本编辑器的问题，2.5.x的时候是正常的。 ![clipboard_image_1648534066630](https://user-images.githubusercontent.com/26681854/160565831-852fa122-d8f6-4c6f-afd8-7ed39df0bfac.png)

js代码格式化缩进会顶格
eslint还是没生效

<img width="373" alt="image" src="https://user-images.githubusercontent.com/6396793/160734748-e62cdea5-3625-41a4-904c-8adf2898d327.png">

**Comment by pagnkelly** [comment]
v0.2.8解决了此问题，eslint可以看readme如何接入。eslint文档后续推出敬请期待。如果解决了你的问题，麻烦给个star感谢🙏
