### ISSUE TITLE
Save & Format issue: need too much time to format and save code

### ISSUE THREAD

**Issue by LikeDreamwalker** [mpx-ecology/vscode-mpx#54]
![D-Chat_20220824152344](https://user-images.githubusercontent.com/45194556/186356962-c8668148-406f-4b80-85aa-169210a85f1c.png)
如图，不太确定是在哪个版本开始出现类似问题的，表现是在保存代码时MPX插件需要大量时间执行format操作以修复ESLint错误和格式化。绝大多数情况需要10秒左右保存成功，极少数情况下保存失败，之后会导致MPX插件的所有功能失效。
VS Code: 1.70.2
MPX: 0.2.9

**Comment by pagnkelly** [comment]
应该不是mpx的功能，你可以把你的vscode settings发出来看下，或许是其他的配置导致的

**Comment by LikeDreamwalker** [comment]
我查了一下，貌似的确不是MPX的问题，但是Vetur会有类似的问题，会和MPX的实现有关系吗？我印象中MPX的实现是参考了Vetur的……

**Comment by pagnkelly** [comment]
确实参考了Vetur，如果遇到一些异常，可以尝试先禁用Vetur，排除是Vetur影响的。但是这个保存format应该不是vscode-mpx导致的

**Comment by LikeDreamwalker** [comment]
在关闭Vetur之后（我的配置中没有使用Vetur作为mpx或者其他文件的格式化器），有了 一点 改善但该问题依然存在……感觉更像是ESLint的修复依赖于网络或是缓存等内容

**Comment by pagnkelly** [comment]
可以尝试关闭mpx的插件，看还有吗。看网上说是vscode发请求了导致的，还有关掉
`"editor.codeActionsOnSave": {

    "source.fixAll.eslint": true

  },`
可以解决

**Comment by LikeDreamwalker** [comment]
有点难定位，关闭auto fix后的确速度更快了但是eslint修复也失效了😂

**Comment by pagnkelly** [comment]
感觉是eslint和vscode联动的问题，不过没办法，还是得需要这个eslint插件的
