### ISSUE TITLE
最新的0.2.12版本不支持格式化，回退版本就好了

### ISSUE THREAD

**Issue by xifan052** [mpx-ecology/vscode-mpx#57]
![image](https://user-images.githubusercontent.com/34504196/190046057-612b23e7-b8d5-461d-86e1-c1f6fcc0a069.png)
![1663122994312](https://user-images.githubusercontent.com/34504196/190045914-efdc8683-ae3b-438e-a589-156295921d39.jpg)
![image](https://user-images.githubusercontent.com/34504196/190045959-94ffa825-15cd-491b-8665-4d1667465936.png)

**Comment by DestinyZxw** [comment]
+1

**Comment by pagnkelly** [comment]
感谢反馈，0.2.13修复了
