### ISSUE TITLE
可以提供一个自定义代码片段的实例么

### ISSUE THREAD

**Issue by theozhang32** [mpx-ecology/vscode-mpx#58]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/92575976/233932451-cc1cacab-7277-4711-aba2-b887aaf7aec5.png">

我做如下配置不生效

**Comment by pagnkelly** [comment]
https://github.com/mpx-ecology/vscode-mpx/blob/master/server/src/modes/mpx/mpxSnippets/default.mpx

**Comment by theozhang32** [comment]
> https://github.com/mpx-ecology/vscode-mpx/blob/master/server/src/modes/mpx/mpxSnippets/default.mpx

谢谢
