### ISSUE TITLE
Cause too much time to show code tips

### ISSUE THREAD

**Issue by LikeDreamwalker** [mpx-ecology/vscode-mpx#59]
Related issues: https://github.com/mpx-ecology/vscode-mpx/issues/54
I just tried local and found out mpx-plugin will need a lot of time (about seconds) to show code tips. And it's easy to reproduce by stopping using mpx-plugin in `.mpx` files.
And I have already found some related issues in some versions of Vetur. Is there any plan to solve this issue? Really kind of annoying.
Current version: 0.2.13

**Comment by LikeDreamwalker** [comment]
And in the last issue, we thought it might be caused by the ESLint plugin. I think Vetur might have the same issue, and they fix it, so maybe we can find something. 🤔

**Comment by pagnkelly** [comment]
Okay, we will take a look later. If you are in a hurry, you can try to see how to implement Vetur and then implement it in vscode mpx. Welcome to submit the PR

**Comment by LikeDreamwalker** [comment]
> 

Thanks, and I will try to share what I found in Vetur later.

**Comment by LikeDreamwalker** [comment]
I didn't find anything useful, but everything turned normal when I started an old and light project.
So I wonder if it is related to the project's dependency when it has too many node modules, and the plugin must read all files to know what to link. The old Vetur had this issue, and they fixed it, but it seems like this issue still happens in Vetur these days, so I am not sure if this is the reason.

**Comment by pagnkelly** [comment]
```
  "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
```
我觉得你可能设置了这个导致的，关闭就不存在那个问题的，其原因根本还是vscode的问题
