### ISSUE TITLE
mpx格式化报错

### ISSUE THREAD

**Issue by dev-2099** [mpx-ecology/vscode-mpx#60]
复现步骤:
vscode及其相关插件均为最新版，window10 22h2系统。

1、demo解压后npm install 安装依赖包
2、vscode下方的控制台切换到“输出”tab，下拉框选择“mpx Language Server”
3、打开项目的pages/home文件，随便打几个空格，按Ctrl+S保存页面，或者右键格式化文件，触发mpx的格式化操作
4、此时可在“输出”tab下看到"Prettier format failed"，[Error - 19:09:33] prettierModule.resolveConfig.sync is not a function
"Prettier format failed"。

以下是参考：
5、打开vscode设置，加入 "files.associations": { "*.mpx": "vue" }，重复上述3步骤，则无报错信息，home.mpx文件可正常被格式化。
6、撤销步骤5，打开package.json文件，更改以下包的版本号为
"eslint-plugin-prettier": "4.2.1",
"prettier": "2.8.8",
重新npm install 后，重复步骤3，则无报错信息，home.mpx文件可正常被格式化。

结论：
mpx貌似不兼容prettier v3.0.x版本，但vue并无此问题。

[mpx-demo.zip](https://github.com/mpx-ecology/vscode-mpx/files/12428818/mpx-demo.zip)

**Comment by pagnkelly** [comment]
prettier 删掉就好了，目前内置了2.6.2版本的prettier
