### ISSUE TITLE
mpx/eqeqeq 规则无波浪线提示

### ISSUE THREAD

**Issue by dev-2099** [mpx-ecology/vscode-mpx#61]
1、在.eslintrc.js文件的rules节点下添加"mpx/eqeqeq": ["error", "always"]规则
2、随便一个mpx页面，加入一行代码测试效果，例如：`<view wx:if="{{userType==0}}"></view>`

期待效果是：`<view wx:if="{{userType==0}}"></view>`下面会有一个红色的波浪线提示不符合mpx/eqeqeq规则。

实际效果是：`<view wx:if="{{userType==0}}"></view>`下面没有红色的波浪线提示，并且如果此页面有其他不符合规则的，也会一并不提示，当把`<view wx:if="{{userType==0}}"></view>`注释掉或者改成`<view wx:if="{{userType===0}}"></view>`后，其他不符合规则的模板代码则正常显示波浪线提示。

**Comment by pagnkelly** [comment]
需要提供eslintrc

**Comment by pagnkelly** [comment]
https://mpx-ecology.github.io/eslint-plugin-mpx/user-guide/#%E7%BC%96%E8%BE%91%E5%99%A8%E9%9B%86%E6%88%90

**Comment by dev-2099** [comment]
补充复现代码，vscode为最新版，vscode中已设置esling检查如下：
"eslint.format.enable": true,
"eslint.validate": ["vue", "mpx", "jsx", "html", "JavaScript", "TypeScript"],
mpx插件为 v0.2.13 版

[mpx-demo.zip](https://github.com/mpx-ecology/vscode-mpx/files/12656059/mpx-demo.zip)

复现步骤
1、npm install 安装所需依赖。
2、打开pages/home.mpx页面，此时可见`<view wx:for="{{item in items}}"></view>`下方有红色波浪线提示，鼠标放上去悬浮提示不符合eslint[mpx/valid-wx-key]规则。
3、去除`<view wx:if="{{userType==0}}"></view>`这一行的注释，此行未能显示红色的波浪线，并且原本第2步显示出来的波浪线也不见了。

期待结果
1、mpx/eqeqeq 规则能正确提示错误。
2、另请帮忙看看 import 了 onLoad 函数，单页面并未使用，为啥也没提示出来，正确的应该是颜色变淡才对。

**Comment by pagnkelly** [comment]
1.eslint 版本降为7
2.
![image](https://github.com/mpx-ecology/vscode-mpx/assets/16016300/f22c961d-1452-427f-b232-db84477212df)
