### ISSUE TITLE
双等号会导致高亮显示异常

### ISSUE THREAD

**Issue by MrBaoquan** [mpx-ecology/vscode-mpx#62]
使用==
![image](https://github.com/mpx-ecology/vscode-mpx/assets/36908656/c64d286d-eb3a-439b-b1a5-4ec49a14d88e)

正常情况应该是这样的
![image](https://github.com/mpx-ecology/vscode-mpx/assets/36908656/8f413c3b-4971-4fb0-a500-be76293ae8fa)

**Comment by pagnkelly** [comment]
未能复现，麻烦提供下代码，另外检查下是否开启了vue的插件导致影响mpx文件高亮

**Comment by MrBaoquan** [comment]
已解决: 双等号两边加空格就好了
