### ISSUE TITLE
跳转定义 不能跳转模版定义么

### ISSUE THREAD

**Issue by CyJaySong** [mpx-ecology/vscode-mpx#63]
RT

**Comment by pagnkelly** [comment]
js只能跳转到js定义的位置，组件只能跳转到组件定义的位置，不太理解模版定义

**Comment by pagnkelly** [comment]
这个我们研究下，看能否实现

**Comment by CyJaySong** [comment]
感谢

**Comment by pagnkelly** [comment]
0.2.14已实现

**Comment by CyJaySong** [comment]
<img width="641" alt="image" src="https://github.com/mpx-ecology/vscode-mpx/assets/29367599/ca4c98d7-056a-40dc-88f4-49bff93e1813">
<img width="617" alt="image" src="https://github.com/mpx-ecology/vscode-mpx/assets/29367599/d3a7742e-14d4-495c-a729-b0d8ac73e8a2">

**Comment by pagnkelly** [comment]
不支持自定义路径，插件无法知道你自己定义的根目录

**Comment by CyJaySong** [comment]
那要放在哪里呢

**Comment by pagnkelly** [comment]
相对路径或者node_modules下的可以，例如../../components/list.mpx

**Comment by pagnkelly** [comment]
不行的，实现有困难

**Comment by CyJaySong** [comment]
有困难咱们就攻克困难嘛😄

**Comment by CyJaySong** [comment]
使用相对路径只能从下面的script块跳转定义，不能从template块跳转定义
<img width="736" alt="image" src="https://github.com/mpx-ecology/vscode-mpx/assets/29367599/6b173131-0c23-440d-82a9-fb2528e018f0">

**Comment by pagnkelly** [comment]
确认路径是否正确，我这看着可以的

**Comment by CyJaySong** [comment]
路径确实是对的，`script`块这里就能点过去的

**Comment by pagnkelly** [comment]
我这确实可以的，不行重启一下ide

**Comment by CyJaySong** [comment]
重启了也这样

**Comment by pagnkelly** [comment]
那很奇怪，弄一个删了node_modules的压缩包给我吧

**Comment by pagnkelly** [comment]
确实存在问题，标签大小写转换错误，都用小写字母可以使用，今晚添加大写组件名称支持

**Comment by CyJaySong** [comment]
好的，感谢

**Comment by CyJaySong** [comment]
> tsconfig.json或者jsconfig.json里面定义了根目录也不行么

这个要是能搞定就好了，写的时候还要去输要往前翻几个目录😂

**Comment by pagnkelly** [comment]
这个立马搞定不了了，后面再看
