### ISSUE TITLE
mpx/no-deprecated-html-element-is 在这种情况下也报错 <template is="skeleton" />

### ISSUE THREAD

**Issue by li-kang** [mpx-ecology/vscode-mpx#9]
详见下图：
<img width="726" alt="截屏2020-10-28 下午2 44 01" src="https://user-images.githubusercontent.com/3938052/97403876-25e7b980-1930-11eb-9863-fdce2f21b5d9.png">

**Comment by pagnkelly** [comment]
> 详见下图：
> <img alt="截屏2020-10-28 下午2 44 01" width="726" src="https://user-images.githubusercontent.com/3938052/97403876-25e7b980-1930-11eb-9863-fdce2f21b5d9.png">

感谢反馈，0.1.21版本已修复  https://marketplace.visualstudio.com/_apis/public/gallery/publishers/pagnkelly/vsextensions/mpx/0.1.21/vspackage
